# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
#    App\:
#        resource: '../../src/*'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    AppBundle\Controller\DefaultController:
        tags: ['controller.service_arguments']
#
#    App\Manager\ContactMessageManager:
#      arguments:
#          $entityManager: '@doctrine.orm.entity_manager'
#
#    App\Admin\ContactMessageAdmin:
#      arguments:
#          $title: '%sulu_admin.name%'
#      tags: [sulu.admin]
